### ISSUE TITLE
Installing kazoo on Amazon AWS with simple-installer issue

### ISSUE THREAD

**Issue by bizmedia** [2600hz/community-scripts#46]
I'm trying install  Kazoo Single Server on Amazon AWS with simple-installer on Centos 6.5.
Scripts interrupt installing and hangs up when "Starting ecallmgr":

```shell
Starting kamailio:                                         [ OK ]
 - Restarting Whapps with: service kz-whistle_apps restart  
Starting whistle_apps:                                     [ OK ]
 - Restarting ecallmgr with: service kz-ecallmgr restart  
Starting ecallmgr:                                         [ OK ]
 - Waiting for whapps to start by polling: /opt/kazoo/utils/sup/sup whapps_controller list_apps
```
hangs up here
How can i solve issue

**Comment by sangramrath** [comment]
Same issue here as well. Any ideas? I feel it could be related to IPs (AWS has different internal and external IP)

**Comment by sangramrath** [comment]
Solved: Press cntrl + c to interrupt the installation. It will tell you how you can resume the installation. Replace the internal ip of AWS instance with public IP (in file /var/www/html/kazoo-ui/config/config.js file. Save file and restart the installation from the last point.

**Comment by saurabhsharma** [comment]
I am setting this on Rackspace server and getting same issue. I have check "/var/www/html/kazoo-ui/config/config.js" and its public IP there. What should I do?

**Comment by saurabhsharma** [comment]
Anybody there?

**Comment by saurabhsharma** [comment]
Kazoo Team you should be more active on community. 

Try this - 

Edit your /etc/hosts file and add 

127.0.0.1 yourhostname

Do not add .com with yourhostname.

**Comment by jamesaimonetti** [comment]
This space isn't monitored for support. I'd suggest posting to the mailing list or filing a ticket if you think there's a bug or have a feature request. You can, of course, issue a pull request against the appropriate repository if you want to contribute the fix/feature you'd like to see as well!
