### ISSUE TITLE
setup_common: line 143: interfaces[@]: unbound variable unknown error

### ISSUE THREAD

**Issue by rhetor22** [2600hz/community-scripts#62]
Trying to install on an OpenVZ CentOS 6.5 VPS... I get this error on install:

setup_common: line 143: interfaces[@]: unbound variable unknown error

I have two interfaces, venet0 and venet0:0.  venet0 is 127.0.0.1 and venete0:0 is public static IP...

Any hints?

**Comment by lazedo** [comment]
this is related to your interface name, not an issue here.
thanks

**Comment by reillychase** [comment]
Same issue on RHEL 7.2. My interfaces are eth0 and lo though. Solution?
