### ISSUE TITLE
Kamailio does not start after installation

### ISSUE THREAD

**Issue by samarnath** [2600hz/community-scripts#65]
Hello,

Kamailio does not starts after install. I have tried groupadd kamailio but no results. Can someone help me to fix this issue.

Regards
Sam

**Comment by lazedo** [comment]
there are no known issues with kamailio.
please post to google group referring version, steps to reproduce.
Thank you.

**Comment by samarnath** [comment]
This is the error, can you check please.

Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !MY_HOSTNAME!call.dvlgroups.com!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !MY_IP_ADDRESS!183.82.44.138!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !MY_AMQP_URL!kazoo://guest:guest@127.0.0.1:5672!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !MY_WEBSOCKET_DOMAIN!2600hz.com!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !UDP_SIP!udp:183.82.44.138:5060!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !TCP_SIP!tcp:183.82.44.138:5060!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !TLS_SIP!tls:183.82.44.138:5061!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !UDP_ALG_SIP!udp:183.82.44.138:7000!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !TCP_ALG_SIP!tcp:183.82.44.138:7000!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !TLS_ALG_SIP!tls:183.82.44.138:7001!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !TCP_WS!tcp:183.82.44.138:5064!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !UDP_WS_SIP!udp:183.82.44.138:5064!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !TLS_WSS!tls:183.82.44.138:5065!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !UDP_WSS_SIP!udp:183.82.44.138:5065!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !KAZOO_DB_URL!text:///etc/kazoo/kamailio/dbtext!g
Jun 23 20:59:38 dvl kamailio: INFO: <core> [ppcfg.c:82]: pp_subst_add(): ### added subst expression: !MAX_WHILE_LOOPS!500!g
Jun 23 20:59:38 dvl kamailio: WARNING: <core> [cfg.y:3409]: warn_at(): warning in config file /etc/kazoo/kamailio/default.cfg, line 83, column 16-18: sctp support not compiled in
Jun 23 20:59:38 dvl kamailio: WARNING: <core> [cfg.y:3412]: warn_at(): warning in config file /etc/kazoo/kamailio/registrar-role.cfg, line 136, column 24: non-int expression (you might want to use casts)#012
Jun 23 20:59:38 dvl kamailio: : <core> [cfg.y:3435]: yyerror_at(): parse error in config file /etc/kazoo/kamailio/default.cfg, line 698, column 45: syntax error
Jun 23 20:59:38 dvl kamailio: : <core> [cfg.y:3435]: yyerror_at(): parse error in config file /etc/kazoo/kamailio/default.cfg, line 700, column 125: bad expression
Jun 23 20:59:38 dvl kamailio: : <core> [cfg.y:3435]: yyerror_at(): parse error in config file /etc/kazoo/kamailio/default.cfg, line 700, column 125: invalid failure_route statement
Jun 23 20:59:38 dvl kamailio: : <core> [cfg.y:3435]: yyerror_at(): parse error in config file /etc/kazoo/kamailio/default.cfg, line 701, column 9:
Jun 23 20:59:38 dvl kamailio: WARNING: <core> [mem/q_malloc.c:429]: qm_free(): WARNING:qm_free: free(0) called from kazoo: kz_amqp.c: kz_amqp_destroy_server(577)
Jun 23 20:59:38 dvl kamailio: WARNING: <core> [mem/q_malloc.c:429]: qm_free(): WARNING:qm_free: free(0) called from kazoo: kazoo.c: mod_destroy(483)
Jun 23 20:59:38 dvl kamailio: WARNING: <core> [mem/q_malloc.c:429]: qm_free(): WARNING:qm_free: free(0) called from kazoo: kazoo.c: mod_destroy(484)
